### PR TITLE
Add /dev/world/2024

### PR DESCRIPTION
**Pull request by KabukiAdam**
Add /dev/world/2024

### CODE REVIEW

**Comment by davedelong** [comment]
Hey @KabukiAdam, can you check to see if the conference name needs escaping?

**Comment by KabukiAdam** [comment]
@davedelong The 2019 version of this same conference has the name listed the same way with non-escaped forward slashes, and that looks fine on the web site, so I think it's fine (although I'm no YAML syntax expert).

```
- name: /dev/world/2019
  link: https://devworld.com.au
  start: 2019-09-02
  end: 2019-09-04
  location: 🇦🇺 Melbourne, Australia
  cocoa-only: true
  cfp:
    link: https://docs.google.com/forms/d/e/1FAIpQLSfMy_CVigYeioDJ9mpoLX41TuVGbyDBmBrG-aqFAfX4ZlmENw/viewform
    deadline: 2019-06-05
```

**Review by davedelong — APPROVED** [review]

**Comment by davedelong** [comment]
Thanks for checking! I'll keep an eye on it to make sure the site builds correctly.

**Comment by davedelong** [comment]
Yep, it worked. Thanks again!

**Pull request merged**
