### PR TITLE
Added all ticket prices for conferences

### PR DESCRIPTION
**Pull request by funky-monkey**
I've added all the tickets costs in a new column. I also tried first to have separate columns for the different types of ticket, but there is too much variation in the ticket types conferences offer. 
So now I just list all the prices. 

Enjoy!

### CODE REVIEW

**Comment by icanzilb** [comment]
I can see this information might be useful, but on the other hand, it might skew people's preference based solely on price comparison. 

Let me give an example - if the table included each event's schedule, speakers, and ticket price people will be well informed and decide which event to look up in detail and eventually visit. Given only a price that would be the sole trait to compare events.

**Comment by Lascorbe** [comment]
Thank you @funky-monkey for the PR! 🍻 

I can see the advantage of having this information in the table, but as @icanzilb points out, this might make people to choose based on price instead o comparing every event as whole.

Right now, I'm not 100% of what to do, so let me put this on hold while I give it some thoughts and ask more people to see what they also think.

**Comment by funky-monkey** [comment]
Thanks :)

 From a personal perspective; I make a choice that is based partly on 
what an event costs because I want to know what is within my price 
range. I've had too many time that I get really enthusiastic about an 
event, the program and the speakers and then I find out it is very 
expensive. (Think RWDevCon, WWDC)

 From a business perspective; Like many companies, we have event budgets 
for a year - having the price visible makes me able to give my boss a 
rough estimate for what I can visit and how many events I can/want to 
attend. If my boss pays and an event is $1500+ means I can only visit 
one or two a year...

So yes, of course price is a part of picking an event, but ultimately it 
comes down to speakers and the talks.

Love to hear what you think,

Best,

Sidney

**Comment by Abizern** [comment]
I think the choice depends on what the point of the information is.

 If it's mainly to provide information about upcoming conferences and CfP deadlines, then the price is unimportant, unless it provides some indication of the audience engagement. 

If it's to show upcoming conferences and prices, then the price information is important, except, as @icanzilb says, it's misleading without further context.

**Comment by icanzilb** [comment]
I agree that the entry price is important. My point is that this PR adds ONLY the price to te conference list making it the ONLY criteria to chose between events.

As said - if the PR adds the schedule, speakers and price I’d be very much in favor but adding only the price turns this handy conference list into a price comparisson.

**Comment by funky-monkey** [comment]
I can add two columns for schedule and speakers? With links to those pages. Idea?

**Comment by icanzilb** [comment]
ok, last thing I'm saying because I feel like I'm repeating myself. the list already includes a link to the conference website. it's where ppl can find all the information - price, schedule, and speakers. for me adding the price here in the repo turns the list into a price comparison - in my pov is enough that there is a link to the event website where ppl can find all they are interested in.

**Comment by funky-monkey** [comment]
Ok, sorry... I'll cancel this pr and leave the fork in my own repo.

**Pull request closed without merging**
