### PR TITLE
Add Swift TO Conference (Aug 2023)

### PR DESCRIPTION
**Pull request by bitwit**

### CODE REVIEW

**Comment by Lascorbe** [comment]
amazing thank you @bitwit! 🍻

**Comment by cgrail** [comment]
Hi @bitwit 
I've also added the conference to our site: https://github.com/tech-conferences/conference-data/pull/5194

https://confs.tech

**Comment by bitwit** [comment]
Thank you @Lascorbe . I don't see the conference listed on the website, is there a pipeline issue?

**Comment by davedelong** [comment]
@bitwit I'm not sure what the issue was, but I forced the site to rebuild and it's showing up now. Thanks for checking!

**Comment by Lascorbe** [comment]
thank you both for reporting and fixing the issue! 🤗

**Pull request merged**
