### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fabb**
added some upcoming conferences

### CODE REVIEW

**Comment by Lascorbe** [comment]
Thanks for the PR! But it needs ` n/a |` (or the specific dates) at the end of all the additions (it's the CfP column).

**Comment by fabb** [comment]
Sure, will do!

Btw. have you thought about adding this list to the awesome list? https://github.com/sindresorhus/awesome

**Comment by Lascorbe** [comment]
Thanks! 🍻 

You mean https://github.com/RichardLitt/awesome-conferences ?

**Comment by fabb** [comment]
HM no, I meant like thos one adding a link to the awesome list, and a link to it to the awesome list, but it seems that it is not (or no longer?) part of the awesome list, strange.
https://github.com/amobconf/awesome-mobile-conferences/blob/master/README.md

Whatever.

**Pull request merged**
