### PR TITLE
🇳🇱 Add DO iOS 2023

### PR DESCRIPTION
**Pull request by xavierLowmiller**
(Not sure how to count the additional workshop day on November 7th)

### CODE REVIEW

**Comment by jeroenleenarts** [comment]
It is fine like this I think. The workshop day is a small addition making the trip extra valuable for intercontinental visitors. Only 40 workshop spots anyways.

**Comment by jeroenleenarts** [comment]
Please add the CFP link: https://www.papercall.io/do-ios-2023
With the deadline of: 31-08-2023

**Comment by xavierLowmiller** [comment]
Thanks for the hint! It's added as part of cdaf8c2

**Comment by Lascorbe** [comment]
thank you!

**Pull request merged**
