### PR TITLE
Add iOS Conf SG 2020

### PR DESCRIPTION
**Pull request by vincent-pradeilles**

### CODE REVIEW

**Comment by fassko** [comment]
They haven't updated their website yet though

**Comment by vincent-pradeilles** [comment]
> They haven't updated their website yet though

Yeah, to be honest I wasn't sure if I should make the PR given that the website has yet to be updated. 

The reason that I went through is that their CFP is currently on-going and they are actively promoting it, so I figured that people might be interested in seing it listed on the website. https://twitter.com/iosconfsg/status/1158618972540948480

**Comment by fassko** [comment]
I think let's wait once they update their website. I think most of the folks click website link rather than CFP.

**Comment by subhransu** [comment]
Thanks, @vincent-pradeilles for creating the PR.
@fassko Let me update the website.

**Comment by subhransu** [comment]
I have updated the site with a link to the CFP.

**Comment by fassko** [comment]
I guess we can merge this?

**Comment by Lascorbe** [comment]
Done, thank you!

**Pull request merged**
