### PR TITLE
Adding SwiftAveiro

### PR DESCRIPTION
**Pull request by FranciscoAmado**
Hey there!

Just adding SwiftAveiro to the list.
It's happening in [June 21st and 22nd](https://twitter.com/SwiftAveiro/status/958096587321954305).
Usually this a conference with a different format, more based in small workshops.

### CODE REVIEW

**Comment by Lascorbe** [comment]
Thanks @FranciscoAmado! 🍻

**Comment by Lascorbe** [comment]
Whoops, can you add ` n/a |` to the end of the line? Otherwise it'll have a missing column.

**Comment by FranciscoAmado** [comment]
Oh shoot.. of course. Totally missed that 😅
Thanks!

**Comment by Lascorbe** [comment]
Thanks!! 😊

**Pull request merged**
