### PR TITLE
Remove Mobile Conf Thailand 2020

### PR DESCRIPTION
**Pull request by zntfdr**
Another victim of covid 😢

### CODE REVIEW

**Comment by davedelong** [comment]
Do you have a source for this? I don't see any announcement on twitter or their website.

**Comment by zntfdr** [comment]
I'm friends with the organizers, they haven't announce it publicly, but as you can see from [their website](http://mobileconfth.com) it's supposed to happen in 20 days and all tickets + lineup are still from 2019.

I will ping them to put something up 👍🏻

**Comment by macbaszii** [comment]
I'm the lead organizer of this conference, sorry for no official announcement.
I can say here that the conference is gone. Thanks @zntfdr for following this up to me.

**Comment by davedelong** [comment]
@macbaszii thanks for confirming!

**Comment by zntfdr** [comment]
For the sake of completion, here's the official announcement:
https://twitter.com/mobileconfth/status/1292842073234665474

Many thanks @macbaszii for the prompt response! 🙏🏻

**Pull request merged**
