### PR TITLE
Add Macoun

### PR DESCRIPTION
**Pull request by below**
Added Macoun in Frankfurt, Germany

### CODE REVIEW

**Comment by Lascorbe** [comment]
@below this list only admits all-English conferences (or where they provide real-time translation like try Swift Tokyo), I think Macoun is in German only, right?

**Comment by cgrail** [comment]
Hi @below,

I've also added the conference to our site: 
https://github.com/tech-conferences/conference-data/pull/5026

https://confs.tech

**Comment by below** [comment]
> @below this list only admits all-English conferences (or where they provide real-time translation like try Swift Tokyo), I think Macoun is in German only, right?

Right :(

**Comment by Lascorbe** [comment]
thank you @below! I'm closing this PR then

**Pull request closed without merging**
