### PR TITLE
Add Swift India

### PR DESCRIPTION
**Pull request by atomicbird**

### CODE REVIEW

**Comment by davedelong** [comment]
Is this a conference for general mobile development? The name implies it’s a “cocoa only” conference.

**Comment by atomicbird** [comment]
I wasn't sure what "cocoa only" implied. I thought a Swift-focused conference wouldn't necessarily be all Cocoa. If it's either Cocoa or "general mobile" then it's Cocoa-only.

**Comment by davedelong** [comment]
Great, thanks!

**Comment by Lascorbe** [comment]
@atomicbird yes, cocoa-only comes from pre-swift times, which means the conference it's all and only about Apple technologies.

**Pull request merged**
