### PR TITLE
Fix type in name SyncSwift -> AsyncSwift

### PR DESCRIPTION
**Pull request by Abizern**

### CODE REVIEW

**Comment by cgrail** [comment]
@Abizern is it really AsyncSwift. On the homepage I can see both AsyncSwift and SyncSwift used. But I don't speak Korean.
https://github.com/tech-conferences/conference-data/pull/4816

**Comment by Abizern** [comment]
> @Abizern is it really AsyncSwift. On the homepage I can see both AsyncSwift and SyncSwift used. But I don't speak Korean.
> [tech-conferences/conference-data#4816](https://github.com/tech-conferences/conference-data/pull/4816)

I think you are right. I was looking at the link address, but the page shows SyncSwift. I'l close this PR. 

Thank you!

**Comment by cgrail** [comment]
Well I'm not sure. The translation says this:
```
SyncSwift 2022 Nesting, Nest
AsyncSwift's first conference.
```
So I'll also close my PR.

**Comment by cgrail** [comment]
It's confusing

**Comment by M1zz** [comment]
I can help you
there is a group async swift
they do two types of conference 

async swift - irregular
sync swift - regular

November -> Sync swift

**Comment by cgrail** [comment]
Cool. Thanks a lot for the clarification.

**Pull request closed without merging**
